services:
  - type: web
    name: emotion-detector-webapp
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: MODEL_MODE
        value: deepface
      - key: FLASK_ENV
        value: production