services:
  - type: web
    name: emotion-detector-webapp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python emotion_detector/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: MODEL_MODE
        value: deepface
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000